### ISSUE TITLE
other SOAT model

### ISSUE THREAD

**Issue by lyj0823** [liulingbo918/CMMPNet#1]
thanks for your great work! How can i reimplemented other start of ther art model result?

**Comment by liulingbo918** [comment]
You can obtain the network architectures of other models from [link](https://github.com/suniique/Leveraging-Crowdsourced-GPS-Data-for-Road-Extraction-from-Aerial-Imagery/tree/master/networks) and put them into our project folder ‘networks’.

**Comment by lyj0823** [comment]
thanks for your reply，I'll have a try!
